#!/usr/bin/env bash

LS_ERROR="EXVM couldn't find ls"
SED_ERROR="EXVM couldn't find sed"
GREP_ERROR="EXVM couldn't find grep"
SORT_ERROR="EXVM couldn't find sort"
HEAD_ERROR="EXVM couldn't find head"

LS_PATH=$(unalias ls &> /dev/null; command -v ls) || exvm_warn "$LS_ERROR" || return 1
SED_PATH=$(unalias sed &> /dev/null; command -v sed) || exvm_warn "$SED_ERROR" || return 1
GREP_PATH=$(unalias grep &> /dev/null; command -v grep) || exvm_warn "$GREP_ERROR" || return 1
SORT_PATH=$(unalias sort &> /dev/null; command -v sort) || exvm_warn "$SORT_ERROR" || return 1
HEAD_PATH=$(unalias head &> /dev/null; command -v head) || exvm_warn "$HEAD_ERROR" || return 1
