#!/usr/bin/env bash

# remove alter the PATH variable, leaving only the system version of ELIXIR available.
exvm_system() {
    ## use sed "s,<pattern>,<replacement>" To remove any reference of elixir, duplicated ::,: from the beginning and from the end of path
    PATH="$(echo $PATH | sed -e "s,$ELIXIR_ROOT/bin,,g ; s,^:,, ; s,::,:,g ; s,:$,,")"
    export PATH
    exvm_dev_info "PATH => $PATH"
}
